#!/bin/sh

git_work_tree_path=/var/www/pubst/prototype
GIT_WORK_TREE=$git_work_tree_path git checkout -f

commitname=`git log -n 1 --pretty=format:%cn`
commitdate=`git log -n 1 --pretty=format:%cd`

# runs script that converts md to website
python $git_work_tree_path/generate_website.py

# echo $commitname >> $git_work_tree_path/commitReceived.txt
# echo $commitdate >> $git_work_tree_path/commitReceived.txt
# To Do: use git variables such as date(`%cd`), name(`%cn`)


